/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatermarkRouteImport } from './routes/watermark'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SocialRouteImport } from './routes/social'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProUpgradeRouteImport } from './routes/pro-upgrade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FreeShortsRouteImport } from './routes/free-shorts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as AnimeMarketRouteImport } from './routes/anime-market'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldCupIndexRouteImport } from './routes/world-cup.index'
import { Route as WorldCupPlayRouteImport } from './routes/world-cup.play'
import { Route as ShortsUploadRouteImport } from './routes/shorts.upload'
import { Route as ShortsIdRouteImport } from './routes/shorts.$id'
import { Route as GenerateVideoRouteImport } from './routes/generate.video'
import { Route as GenerateGokuRouteImport } from './routes/generate.goku'
import { Route as AnimeMarketIdRouteImport } from './routes/anime-market.$id'
import { Route as ApiPublicFatoraSuccessRouteImport } from './routes/api/public/fatora/success'
import { Route as ApiPublicCreditsDeductRouteImport } from './routes/api/public/credits/deduct'

const WatermarkRoute = WatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProUpgradeRoute = ProUpgradeRouteImport.update({
  id: '/pro-upgrade',
  path: '/pro-upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeShortsRoute = FreeShortsRouteImport.update({
  id: '/free-shorts',
  path: '/free-shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeMarketRoute = AnimeMarketRouteImport.update({
  id: '/anime-market',
  path: '/anime-market',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldCupIndexRoute = WorldCupIndexRouteImport.update({
  id: '/world-cup/',
  path: '/world-cup/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldCupPlayRoute = WorldCupPlayRouteImport.update({
  id: '/world-cup/play',
  path: '/world-cup/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsUploadRoute = ShortsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ShortsRoute,
} as any)
const ShortsIdRoute = ShortsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShortsRoute,
} as any)
const GenerateVideoRoute = GenerateVideoRouteImport.update({
  id: '/generate/video',
  path: '/generate/video',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateGokuRoute = GenerateGokuRouteImport.update({
  id: '/generate/goku',
  path: '/generate/goku',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeMarketIdRoute = AnimeMarketIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnimeMarketRoute,
} as any)
const ApiPublicFatoraSuccessRoute = ApiPublicFatoraSuccessRouteImport.update({
  id: '/api/public/fatora/success',
  path: '/api/public/fatora/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreditsDeductRoute = ApiPublicCreditsDeductRouteImport.update({
  id: '/api/public/credits/deduct',
  path: '/api/public/credits/deduct',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anime-market': typeof AnimeMarketRouteWithChildren
  '/audio': typeof AudioRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/free-shorts': typeof FreeShortsRoute
  '/login': typeof LoginRoute
  '/pro-upgrade': typeof ProUpgradeRoute
  '/profile': typeof ProfileRoute
  '/shorts': typeof ShortsRouteWithChildren
  '/social': typeof SocialRoute
  '/tasks': typeof TasksRoute
  '/watermark': typeof WatermarkRoute
  '/anime-market/$id': typeof AnimeMarketIdRoute
  '/generate/goku': typeof GenerateGokuRoute
  '/generate/video': typeof GenerateVideoRoute
  '/shorts/$id': typeof ShortsIdRoute
  '/shorts/upload': typeof ShortsUploadRoute
  '/world-cup/play': typeof WorldCupPlayRoute
  '/world-cup/': typeof WorldCupIndexRoute
  '/api/public/credits/deduct': typeof ApiPublicCreditsDeductRoute
  '/api/public/fatora/success': typeof ApiPublicFatoraSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anime-market': typeof AnimeMarketRouteWithChildren
  '/audio': typeof AudioRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/free-shorts': typeof FreeShortsRoute
  '/login': typeof LoginRoute
  '/pro-upgrade': typeof ProUpgradeRoute
  '/profile': typeof ProfileRoute
  '/shorts': typeof ShortsRouteWithChildren
  '/social': typeof SocialRoute
  '/tasks': typeof TasksRoute
  '/watermark': typeof WatermarkRoute
  '/anime-market/$id': typeof AnimeMarketIdRoute
  '/generate/goku': typeof GenerateGokuRoute
  '/generate/video': typeof GenerateVideoRoute
  '/shorts/$id': typeof ShortsIdRoute
  '/shorts/upload': typeof ShortsUploadRoute
  '/world-cup/play': typeof WorldCupPlayRoute
  '/world-cup': typeof WorldCupIndexRoute
  '/api/public/credits/deduct': typeof ApiPublicCreditsDeductRoute
  '/api/public/fatora/success': typeof ApiPublicFatoraSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anime-market': typeof AnimeMarketRouteWithChildren
  '/audio': typeof AudioRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/free-shorts': typeof FreeShortsRoute
  '/login': typeof LoginRoute
  '/pro-upgrade': typeof ProUpgradeRoute
  '/profile': typeof ProfileRoute
  '/shorts': typeof ShortsRouteWithChildren
  '/social': typeof SocialRoute
  '/tasks': typeof TasksRoute
  '/watermark': typeof WatermarkRoute
  '/anime-market/$id': typeof AnimeMarketIdRoute
  '/generate/goku': typeof GenerateGokuRoute
  '/generate/video': typeof GenerateVideoRoute
  '/shorts/$id': typeof ShortsIdRoute
  '/shorts/upload': typeof ShortsUploadRoute
  '/world-cup/play': typeof WorldCupPlayRoute
  '/world-cup/': typeof WorldCupIndexRoute
  '/api/public/credits/deduct': typeof ApiPublicCreditsDeductRoute
  '/api/public/fatora/success': typeof ApiPublicFatoraSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anime-market'
    | '/audio'
    | '/chat'
    | '/dashboard'
    | '/free-shorts'
    | '/login'
    | '/pro-upgrade'
    | '/profile'
    | '/shorts'
    | '/social'
    | '/tasks'
    | '/watermark'
    | '/anime-market/$id'
    | '/generate/goku'
    | '/generate/video'
    | '/shorts/$id'
    | '/shorts/upload'
    | '/world-cup/play'
    | '/world-cup/'
    | '/api/public/credits/deduct'
    | '/api/public/fatora/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anime-market'
    | '/audio'
    | '/chat'
    | '/dashboard'
    | '/free-shorts'
    | '/login'
    | '/pro-upgrade'
    | '/profile'
    | '/shorts'
    | '/social'
    | '/tasks'
    | '/watermark'
    | '/anime-market/$id'
    | '/generate/goku'
    | '/generate/video'
    | '/shorts/$id'
    | '/shorts/upload'
    | '/world-cup/play'
    | '/world-cup'
    | '/api/public/credits/deduct'
    | '/api/public/fatora/success'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anime-market'
    | '/audio'
    | '/chat'
    | '/dashboard'
    | '/free-shorts'
    | '/login'
    | '/pro-upgrade'
    | '/profile'
    | '/shorts'
    | '/social'
    | '/tasks'
    | '/watermark'
    | '/anime-market/$id'
    | '/generate/goku'
    | '/generate/video'
    | '/shorts/$id'
    | '/shorts/upload'
    | '/world-cup/play'
    | '/world-cup/'
    | '/api/public/credits/deduct'
    | '/api/public/fatora/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnimeMarketRoute: typeof AnimeMarketRouteWithChildren
  AudioRoute: typeof AudioRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  FreeShortsRoute: typeof FreeShortsRoute
  LoginRoute: typeof LoginRoute
  ProUpgradeRoute: typeof ProUpgradeRoute
  ProfileRoute: typeof ProfileRoute
  ShortsRoute: typeof ShortsRouteWithChildren
  SocialRoute: typeof SocialRoute
  TasksRoute: typeof TasksRoute
  WatermarkRoute: typeof WatermarkRoute
  GenerateGokuRoute: typeof GenerateGokuRoute
  GenerateVideoRoute: typeof GenerateVideoRoute
  WorldCupPlayRoute: typeof WorldCupPlayRoute
  WorldCupIndexRoute: typeof WorldCupIndexRoute
  ApiPublicCreditsDeductRoute: typeof ApiPublicCreditsDeductRoute
  ApiPublicFatoraSuccessRoute: typeof ApiPublicFatoraSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watermark': {
      id: '/watermark'
      path: '/watermark'
      fullPath: '/watermark'
      preLoaderRoute: typeof WatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-upgrade': {
      id: '/pro-upgrade'
      path: '/pro-upgrade'
      fullPath: '/pro-upgrade'
      preLoaderRoute: typeof ProUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-shorts': {
      id: '/free-shorts'
      path: '/free-shorts'
      fullPath: '/free-shorts'
      preLoaderRoute: typeof FreeShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime-market': {
      id: '/anime-market'
      path: '/anime-market'
      fullPath: '/anime-market'
      preLoaderRoute: typeof AnimeMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world-cup/': {
      id: '/world-cup/'
      path: '/world-cup'
      fullPath: '/world-cup/'
      preLoaderRoute: typeof WorldCupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world-cup/play': {
      id: '/world-cup/play'
      path: '/world-cup/play'
      fullPath: '/world-cup/play'
      preLoaderRoute: typeof WorldCupPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts/upload': {
      id: '/shorts/upload'
      path: '/upload'
      fullPath: '/shorts/upload'
      preLoaderRoute: typeof ShortsUploadRouteImport
      parentRoute: typeof ShortsRoute
    }
    '/shorts/$id': {
      id: '/shorts/$id'
      path: '/$id'
      fullPath: '/shorts/$id'
      preLoaderRoute: typeof ShortsIdRouteImport
      parentRoute: typeof ShortsRoute
    }
    '/generate/video': {
      id: '/generate/video'
      path: '/generate/video'
      fullPath: '/generate/video'
      preLoaderRoute: typeof GenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/goku': {
      id: '/generate/goku'
      path: '/generate/goku'
      fullPath: '/generate/goku'
      preLoaderRoute: typeof GenerateGokuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime-market/$id': {
      id: '/anime-market/$id'
      path: '/$id'
      fullPath: '/anime-market/$id'
      preLoaderRoute: typeof AnimeMarketIdRouteImport
      parentRoute: typeof AnimeMarketRoute
    }
    '/api/public/fatora/success': {
      id: '/api/public/fatora/success'
      path: '/api/public/fatora/success'
      fullPath: '/api/public/fatora/success'
      preLoaderRoute: typeof ApiPublicFatoraSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/credits/deduct': {
      id: '/api/public/credits/deduct'
      path: '/api/public/credits/deduct'
      fullPath: '/api/public/credits/deduct'
      preLoaderRoute: typeof ApiPublicCreditsDeductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnimeMarketRouteChildren {
  AnimeMarketIdRoute: typeof AnimeMarketIdRoute
}

const AnimeMarketRouteChildren: AnimeMarketRouteChildren = {
  AnimeMarketIdRoute: AnimeMarketIdRoute,
}

const AnimeMarketRouteWithChildren = AnimeMarketRoute._addFileChildren(
  AnimeMarketRouteChildren,
)

interface ShortsRouteChildren {
  ShortsIdRoute: typeof ShortsIdRoute
  ShortsUploadRoute: typeof ShortsUploadRoute
}

const ShortsRouteChildren: ShortsRouteChildren = {
  ShortsIdRoute: ShortsIdRoute,
  ShortsUploadRoute: ShortsUploadRoute,
}

const ShortsRouteWithChildren =
  ShortsRoute._addFileChildren(ShortsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnimeMarketRoute: AnimeMarketRouteWithChildren,
  AudioRoute: AudioRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  FreeShortsRoute: FreeShortsRoute,
  LoginRoute: LoginRoute,
  ProUpgradeRoute: ProUpgradeRoute,
  ProfileRoute: ProfileRoute,
  ShortsRoute: ShortsRouteWithChildren,
  SocialRoute: SocialRoute,
  TasksRoute: TasksRoute,
  WatermarkRoute: WatermarkRoute,
  GenerateGokuRoute: GenerateGokuRoute,
  GenerateVideoRoute: GenerateVideoRoute,
  WorldCupPlayRoute: WorldCupPlayRoute,
  WorldCupIndexRoute: WorldCupIndexRoute,
  ApiPublicCreditsDeductRoute: ApiPublicCreditsDeductRoute,
  ApiPublicFatoraSuccessRoute: ApiPublicFatoraSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
