/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProUpgradeRouteImport } from './routes/pro-upgrade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerateVideoRouteImport } from './routes/generate.video'
import { Route as GenerateGokuRouteImport } from './routes/generate.goku'

const ProUpgradeRoute = ProUpgradeRouteImport.update({
  id: '/pro-upgrade',
  path: '/pro-upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateVideoRoute = GenerateVideoRouteImport.update({
  id: '/generate/video',
  path: '/generate/video',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateGokuRoute = GenerateGokuRouteImport.update({
  id: '/generate/goku',
  path: '/generate/goku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pro-upgrade': typeof ProUpgradeRoute
  '/generate/goku': typeof GenerateGokuRoute
  '/generate/video': typeof GenerateVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pro-upgrade': typeof ProUpgradeRoute
  '/generate/goku': typeof GenerateGokuRoute
  '/generate/video': typeof GenerateVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pro-upgrade': typeof ProUpgradeRoute
  '/generate/goku': typeof GenerateGokuRoute
  '/generate/video': typeof GenerateVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/pro-upgrade'
    | '/generate/goku'
    | '/generate/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/pro-upgrade'
    | '/generate/goku'
    | '/generate/video'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/pro-upgrade'
    | '/generate/goku'
    | '/generate/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProUpgradeRoute: typeof ProUpgradeRoute
  GenerateGokuRoute: typeof GenerateGokuRoute
  GenerateVideoRoute: typeof GenerateVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro-upgrade': {
      id: '/pro-upgrade'
      path: '/pro-upgrade'
      fullPath: '/pro-upgrade'
      preLoaderRoute: typeof ProUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/video': {
      id: '/generate/video'
      path: '/generate/video'
      fullPath: '/generate/video'
      preLoaderRoute: typeof GenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/goku': {
      id: '/generate/goku'
      path: '/generate/goku'
      fullPath: '/generate/goku'
      preLoaderRoute: typeof GenerateGokuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProUpgradeRoute: ProUpgradeRoute,
  GenerateGokuRoute: GenerateGokuRoute,
  GenerateVideoRoute: GenerateVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
